import { Megaphone, Code2, Feather, ScrollText, Users, Briefcase, BarChart2, Lightbulb, Shield } from 'lucide-react';
import type { Persona, Challenge } from './types';

export const personas: Persona[] = [
  {
    id: 'marketing-guru',
    name: 'Marketing Guru',
    description: 'Craft compelling campaigns and slogans.',
    icon: Megaphone,
  },
  {
    id: 'software-engineer',
    name: 'Software Engineer',
    description: 'Solve complex coding problems and design systems.',
    icon: Code2,
  },
  {
    id: 'creative-writer',
    name: 'Creative Writer',
    description: 'Weave enchanting stories and characters.',
    icon: Feather,
  },
  {
    id: 'historian',
    name: 'Historian',
    description: 'Analyze past events and uncover hidden truths.',
    icon: ScrollText,
  },
  {
    id: 'hr-manager',
    name: 'HR Manager',
    description: 'Write job descriptions and manage employee relations.',
    icon: Users,
  },
  {
    id: 'project-manager',
    name: 'Project Manager',
    description: 'Plan projects, create timelines, and assign tasks.',
    icon: Briefcase,
  },
  {
    id: 'data-analyst',
    name: 'Data Analyst',
    description: 'Interpret data, identify trends, and create reports.',
    icon: BarChart2,
  },
  {
    id: 'business-analyst',
    name: 'Business Analyst',
    description: 'Analyze processes and recommend improvements.',
    icon: Lightbulb,
  },
  {
    id: 'cybersecurity-expert',
    name: 'Cybersecurity Expert',
    description: 'Identify threats and create security policies.',
    icon: Shield,
  },
];

export const challenges: Challenge[] = [
  // Marketing Guru Challenges
  {
    personaId: 'marketing-guru',
    challengeId: 1,
    title: 'Your task is to craft a prompt that generates a catchy tagline and a short social media ad copy for a new, eco-friendly water bottle.',
    scenario: "AquaPure, an innovative startup, is on the verge of launching 'EarthBottle,' the world's first fully plant-based, compostable water bottle. They're targeting environmentally aware millennials on social media, but their marketing budget is tight. They need a powerful message that resonates instantly and drives pre-orders. A great prompt should ask the AI to consider the target audience and the product's unique selling points to create marketing copy that is both impactful and persuasive.",
  },
  {
    personaId: 'marketing-guru',
    challengeId: 2,
    title: 'Your task is to craft a prompt that asks an AI to define a new, modern brand voice and brainstorm ideas for a launch event for a coffee shop looking to rebrand.',
    scenario: "'The Daily Grind' has been a beloved neighborhood coffee spot for 20 years, known for its quiet, traditional atmosphere. However, with a new co-working space opening across the street, the owner sees an opportunity to attract a younger, professional clientele. They want to rebrand with a more modern, vibrant, and community-focused identity without alienating their loyal customers. Your prompt should guide the AI to suggest a brand voice that feels authentic and event ideas that are both creative and feasible.",
  },
  {
    personaId: 'marketing-guru',
    challengeId: 3,
    title: 'Your task is to write a prompt that generates three different subject lines for an email campaign promoting a new online course on digital photography.',
    scenario: 'An online learning platform is launching a comprehensive course on "Mastering Digital Photography." The target audience is broad, ranging from absolute beginners to amateur photographers looking to improve. The marketing team wants to A/B test different email subject lines to see what generates the highest open rate. Your prompt should ask the AI to create three distinct subject lines, each targeting a different user motivation (e.g., creativity, technical skill, career advancement).',
  },
  {
    personaId: 'marketing-guru',
    challengeId: 4,
    title: 'Your task is to craft a prompt to generate a script for a 30-second video ad for a mobile app that helps users learn a new language.',
    scenario: 'A language-learning app called "LingoLeap" wants to create a short, engaging video ad for YouTube and Instagram. The app uses gamification and AI-powered conversation practice to make learning fun and effective. The ad needs to quickly grab the viewer\'s attention, showcase the app\'s key features, and end with a strong call to action. Your prompt should instruct the AI on the desired tone (energetic and inspiring) and the key visual elements to include.',
  },
  {
    personaId: 'marketing-guru',
    challengeId: 5,
    title: 'Your task is to craft a prompt that generates a blog post outline titled "5 Ways Our New CRM Will Revolutionize Your Sales Process."',
    scenario: 'A B2B software company is launching a new Customer Relationship Management (CRM) tool. They want to create a compelling blog post for their content marketing strategy to attract small and medium-sized businesses. The post should be informative and clearly articulate the benefits of their CRM over competitors. Your prompt should ask the AI to create a detailed outline, including an introduction, five main points with sub-bullets, and a concluding call to action.',
  },
  {
    personaId: 'marketing-guru',
    challengeId: 6,
    title: 'Your task is to craft a prompt to write a press release announcing a partnership between a fashion brand and a famous artist.',
    scenario: 'A luxury handbag brand, "Eterna," is collaborating with a renowned digital artist, "Nexo," for a limited-edition collection. The press release needs to generate buzz in the fashion and art worlds. It should be professional, exciting, and provide quotes from both the brand\'s CEO and the artist. Your prompt should ask the AI to write a complete press release in a standard format, highlighting the innovative nature of the collaboration.',
  },
  {
    personaId: 'marketing-guru',
    challengeId: 7,
    title: 'Your task is to craft a prompt that generates a series of 5 engaging social media posts for the week leading up to a product launch.',
    scenario: 'A company is about to launch "GlowUp," a new vitamin-infused skincare serum. They want to build anticipation on Instagram and Facebook. You need to create a week-long content plan. Your prompt should ask the AI to generate five posts, including a teaser, a behind-the-scenes look, an ingredient spotlight, a user testimonial, and the final launch announcement. The prompt should specify the desired format for each post (e.g., image caption, video idea).',
  },
  {
    personaId: 'marketing-guru',
    challengeId: 8,
    title: 'Your task is to craft a prompt to generate a customer persona for a new brand of organic pet food.',
    scenario: 'A startup is launching "Pawganic," a premium, all-organic dog food. To effectively target their marketing, they need to deeply understand their ideal customer. Your prompt should ask the AI to create a detailed customer persona, including demographics, lifestyle, values, pain points (related to pet care), and their preferred social media channels. The persona should be named "Health-Conscious Hannah."',
  },
  {
    personaId: 'marketing-guru',
    challengeId: 9,
    title: 'Your task is to craft a prompt that rewrites a technical product description into benefit-driven copy for a consumer-facing website.',
    scenario: 'A new smart home thermostat has a product spec sheet full of technical jargon like "dual-band Wi-Fi," "geofencing capabilities," and "advanced PID algorithm." This is meaningless to the average consumer. Your prompt should provide the technical description and ask the AI to translate it into compelling, easy-to-understand copy that focuses on the benefits, such as "saves you money on your energy bill" and "learns your schedule automatically."',
  },
  {
    personaId: 'marketing-guru',
    challengeId: 10,
    title: 'Your task is to craft a prompt to brainstorm a list of potential influencers to partner with for a new line of sustainable athletic wear.',
    scenario: 'A new brand, "TerraFit," is launching a line of workout clothes made from recycled materials. They want to partner with influencers who align with their brand values of sustainability, fitness, and wellness. Your prompt should ask the AI to generate a list of 10 potential influencer profiles, including their niche (e.g., yoga, hiking, zero-waste living), approximate follower count, and a brief justification for why they would be a good fit for the brand.',
  },
  {
    personaId: 'marketing-guru',
    challengeId: 11,
    title: 'Your task is to craft a prompt that generates an FAQ (Frequently Asked Questions) section for a new subscription box service.',
    scenario: 'A company is launching "SnackVerse," a monthly subscription box for international snacks. They anticipate customers will have questions about shipping, customization, billing, and dietary restrictions. Your prompt should ask the AI to generate a list of at least 8 common questions and provide clear, concise answers for the website\'s FAQ page.',
  },
  {
    personaId: 'marketing-guru',
    challengeId: 12,
    title: 'Your task is to craft a prompt that creates a compelling "About Us" story for a family-owned bakery.',
    scenario: 'The "Sweet Kneads Bakery" has been passed down through three generations but has never had a website. The new owner, the founder\'s granddaughter, wants to create an "About Us" page that tells their story and communicates their commitment to quality and community. Your prompt should ask the AI to write a heartwarming brand story that captures the bakery\'s history, passion, and traditional values in about 250 words.',
  },
  // Software Engineer Challenges
  {
    personaId: 'software-engineer',
    challengeId: 1,
    title: 'Your task is to craft a prompt for an AI that takes a function signature and generates clear, concise documentation for it, including parameters, return value, and a code example.',
    scenario: "You're leading a team developing a new open-source library. To ensure its adoption, the documentation must be impeccable. However, the team is small, and writing detailed documentation for every function is slowing down development. You need a way to automate the creation of high-quality documentation to keep the project on track. The prompt should specify the exact format and level of detail required for the documentation.",
  },
  {
    personaId: 'software-engineer',
    challengeId: 2,
    title: 'You are given a buggy Python function. Your task is to craft a prompt that explains the problem and asks an AI to identify the bug and suggest a specific code fix.',
    scenario: 'A critical bug has been reported in your application\'s data processing pipeline. A Python function designed to sort a list of transaction IDs (which can be a mix of numbers and alphanumeric strings) is failing intermittently, leading to incorrect financial reports. The pressure is on to find and fix the issue before the end of the fiscal quarter. Your prompt needs to provide the buggy code and enough context for the AI to accurately diagnose and solve the problem.',
  },
  {
    personaId: 'software-engineer',
    challengeId: 3,
    title: 'Your task is to craft a prompt that generates a set of unit tests for a given JavaScript function using the Jest testing framework.',
    scenario: 'You have written a utility function that validates email addresses. To ensure its reliability and prevent future regressions, you need to write a comprehensive suite of unit tests. The tests should cover valid inputs, invalid inputs, edge cases (e.g., empty strings, null values), and different formats. Your prompt should provide the function code and ask the AI to generate Jest `test` blocks that cover these scenarios.',
  },
  {
    personaId: 'software-engineer',
    challengeId: 4,
    title: 'Your task is to craft a prompt that translates a code snippet from Python to JavaScript.',
    scenario: 'Your team is migrating a service from a Python backend to a Node.js backend. You need to convert a specific data transformation function from Python to modern JavaScript (ES6+). The function involves dictionary manipulation and list comprehensions. Your prompt should provide the Python code and ask the AI to produce an equivalent, idiomatic JavaScript function, explaining any key syntax differences.',
  },
  {
    personaId: 'software-engineer',
    challengeId: 5,
    title: 'Your task is to craft a prompt to explain a complex code snippet to a junior developer.',
    scenario: 'A new developer on your team is struggling to understand a recursive function that traverses a file system tree in your codebase. You need to explain how it works in a clear, step-by-step manner. Your prompt should provide the code and ask the AI to generate an explanation that includes the base case, the recursive step, and how the call stack works in this context, using an analogy if possible.',
  },
  {
    personaId: 'software-engineer',
    challengeId: 6,
    title: 'Your task is to craft a prompt that writes a SQL query to retrieve specific information from a database schema.',
    scenario: 'You are an analyst for an e-commerce company. You have a database with `customers`, `orders`, and `products` tables. You need to write a SQL query to find the top 5 customers who have spent the most money in the last quarter. Your prompt should describe the table schemas (columns, types) and the specific business question, then ask the AI to generate the corresponding SQL query with joins, aggregation, and ordering.',
  },
  {
    personaId: 'software-engineer',
    challengeId: 7,
    title: 'Your task is to craft a prompt to refactor a piece of code to make it more efficient and readable.',
    scenario: 'You have inherited a piece of legacy Java code that uses nested `for` loops to find common elements between two large lists. The code is slow and difficult to understand. You want to refactor it using more modern and efficient data structures, like a `HashSet`. Your prompt should provide the inefficient code and ask the AI to refactor it, explaining the performance benefits of the new approach (e.g., time complexity).',
  },
  {
    personaId: 'software-engineer',
    challengeId: 8,
    title: 'Your task is to craft a prompt that generates a regular expression (regex) for input validation.',
    scenario: 'You are building a sign-up form and need to validate that the user-provided password meets certain criteria: at least 8 characters long, contains at least one uppercase letter, one lowercase letter, one number, and one special character. Your prompt should clearly list these requirements and ask the AI to generate a regex pattern that can be used to enforce them.',
  },
  {
    personaId: 'software-engineer',
    challengeId: 9,
    title: 'Your task is to craft a prompt to design a simple REST API endpoint structure for a new feature.',
    scenario: 'You are designing the backend for a simple blog application. You need to define the REST API endpoints for managing blog posts (CRUD operations: Create, Read, Update, Delete). Your prompt should ask the AI to design the API structure, including the HTTP methods (GET, POST, PUT, DELETE), the URL paths (e.g., `/posts`, `/posts/{id}`), and the expected JSON request/response bodies for each endpoint.',
  },
  {
    personaId: 'software-engineer',
    challengeId: 10,
    title: 'Your task is to craft a prompt to generate boilerplate code for a new React component.',
    scenario: 'You are starting a new feature and need to create a `UserProfile` component in a React application that uses TypeScript and functional components with hooks. The component should fetch user data from an API and display it. Your prompt should ask the AI to generate the boilerplate code for this component, including state management with `useState` and `useEffect` for the API call, and placeholder JSX for rendering the user\'s name and email.',
  },
  {
    personaId: 'software-engineer',
    challengeId: 11,
    title: 'Your task is to craft a prompt that generates a command-line script to automate a repetitive task.',
    scenario: 'Every day, you have to back up a specific directory (`/var/data`), compress it into a `.tar.gz` file with the current date in the filename, and move it to a backup server. This is a repetitive and error-prone manual process. Your prompt should describe this workflow and ask the AI to write a Bash script that automates it completely.',
  },
  {
    personaId: 'software-engineer',
    challengeId: 12,
    title: 'Your task is to craft a prompt to help you choose the right data structure for a specific problem.',
    scenario: 'You are building a feature that requires storing a collection of items, and you will frequently need to check if an item exists in the collection. The order of items does not matter, and there are no duplicates. You are considering using an Array or a Set. Your prompt should describe this requirement and ask the AI to recommend the best data structure in JavaScript, explaining the performance implications (e.g., lookup time) of each choice.',
  },
  // Creative Writer Challenges
  {
    personaId: 'creative-writer',
    challengeId: 1,
    title: 'Your task is to craft a prompt that generates a compelling opening paragraph for a science fiction story about first contact.',
    scenario: 'In the year 2242, Dr. Aris Thorne is the sole inhabitant of the Kepler-186f research outpost, studying alien flora. After months of solitude, he discovers a bioluminescent plant that seems to pulse in response to his movements. He suspects it might be sentient, communicating through patterns of light, a discovery that could change humanity\'s understanding of life in the universe. The prompt should ask the AI to capture the sense of isolation, wonder, and the monumental implications of this discovery in the opening lines.',
  },
  {
    personaId: 'creative-writer',
    challengeId: 2,
    title: 'Your task is to craft a prompt to generate a short, tense, and meaningful dialogue between a knight and a dragon.',
    scenario: 'For centuries, the obsidian dragon Ignis has slumbered in the heart of Mount Cinder, hoarding ancient knowledge. A young, idealistic knight, Lady Elara, has been sent not to slay the beast, but to seek its wisdom to stop a devastating plague. She stands at the entrance of the cavern, her sword sheathed, ready to persuade a creature that has only ever known violence from humankind. The prompt should instruct the AI to write a dialogue that reveals the dragon\'s ancient weariness and the knight\'s desperate hope.',
  },
  {
    personaId: 'creative-writer',
    challengeId: 3,
    title: 'Your task is to craft a prompt that generates a detailed character profile for a fantasy novel.',
    scenario: 'You are writing a fantasy novel and need to create a compelling anti-hero. This character is a disgraced royal guard, exiled for a crime he didn\'t commit, and now works as a cynical mercenary. However, he still secretly adheres to a strict code of honor. Your prompt should ask the AI to create a full character profile, including his name, appearance, key personality traits, backstory, motivations, and internal conflicts.',
  },
  {
    personaId: 'creative-writer',
    challengeId: 4,
    title: 'Your task is to craft a prompt to describe a fantasy city from the perspective of a first-time visitor.',
    scenario: 'A young farmhand arrives for the first time in Aethelgard, the legendary "City of Spires," a metropolis built into the side of a mountain, famous for its glowing crystal towers and bustling sky-bridges. You want to capture the overwhelming sense of awe, wonder, and intimidation. Your prompt should ask the AI to write a sensory-rich, one-paragraph description of the city from the farmhand\'s point of view.',
  },
  {
    personaId: 'creative-writer',
    challengeId: 5,
    title: 'Your task is to craft a prompt that creates a plot outline for a mystery story.',
    scenario: 'You have a basic idea for a detective story: a famous magician is found dead in a locked room on a luxury train. The detective, a retired inspector traveling incognito, must solve the case before the train reaches its destination. Your prompt should ask the AI to generate a three-act plot outline, including the setup (introducing the characters and the crime), the confrontation (the investigation, red herrings, and rising tension), and the resolution (the final reveal and climax).',
  },
  {
    personaId: 'creative-writer',
    challengeId: 6,
    title: 'Your task is to craft a prompt to write a short poem about the changing of the seasons.',
    scenario: 'You want to write a short, evocative poem about the transition from autumn to winter. The poem should focus on the sensory details of this change: the last colorful leaves, the first frost, the smell of woodsmoke, and the feeling of quiet anticipation. Your prompt should ask the AI to write a 12-line poem in free verse that captures this specific mood.',
  },
  {
    personaId: 'creative-writer',
    challengeId: 7,
    title: 'Your task is to craft a prompt to rewrite a fairy tale from the villain\'s perspective.',
    scenario: 'You want to retell the story of "Hansel and Gretel" from the witch\'s point of view. In this version, she is not evil, but a lonely, misunderstood herbalist who is terrified of the encroaching woodsmen destroying her forest home. The children are not innocent victims but are destructive and careless. Your prompt should ask the AI to write a short story (approx. 300 words) that reframes the classic tale from this new perspective.',
  },
  {
    personaId: 'creative-writer',
    challengeId: 8,
    title: 'Your task is to craft a prompt to generate a piece of flash fiction based on a single image.',
    scenario: 'Imagine a photograph of a single, red door standing alone in the middle of a vast, empty desert. There are no walls, no buildings, nothing else in sight. You want to write a very short, mysterious story inspired by this image. Your prompt should describe the image and ask the AI to write a piece of flash fiction (under 200 words) about who might open the door and what lies beyond it.',
  },
  {
    personaId: 'creative-writer',
    challengeId: 9,
    title: 'Your task is to craft a prompt to create a fictional magical spell, including its name, incantation, and effects.',
    scenario: 'In your fantasy world, there is a rare and difficult spell used by illusionists. The spell doesn\'t create a physical object, but rather implants a vivid, shared memory into the minds of everyone within a certain radius. Your prompt should ask the AI to invent a name for this spell, a short (2-4 line) incantation in a poetic style, and a clear description of its visual and mental effects on those targeted.',
  },
  {
    personaId: 'creative-writer',
    challengeId: 10,
    title: 'Your task is to craft a prompt to generate three different story hooks for a horror novel.',
    scenario: 'You want to write a horror novel but are looking for a unique and compelling starting point. Your prompt should ask the AI to generate three distinct story ideas or "hooks." Each hook should be a single paragraph and present a different subgenre of horror (e.g., psychological, supernatural, body horror) and a unique premise to build a story around.',
  },
  {
    personaId: 'creative-writer',
    challengeId: 11,
    title: 'Your task is to craft a prompt to write a scene where a character makes a difficult moral choice.',
    scenario: 'In your post-apocalyptic story, the protagonist, Lena, is the leader of a small group of survivors. They have found a locked bunker with enough food to last them for years, but there is only enough room for her and two others. There are five people in her group, including a small child. Your prompt should ask the AI to write a tense, emotional scene focusing on Lena\'s internal monologue and dialogue as she decides who gets to enter the bunker.',
  },
  {
    personaId: 'creative-writer',
    challengeId: 12,
    title: 'Your task is to craft a prompt that generates a world-building description of a unique ecosystem.',
    scenario: 'You are creating a new alien planet for a sci-fi novel. This planet has a "crystal jungle," where the trees are made of giant, crystalline structures and the fauna are silicon-based lifeforms that feed on geothermal energy. Your prompt should ask the AI to write a 2-3 paragraph description of this ecosystem, detailing the flora, fauna, and the overall environment to help the reader visualize this alien world.',
  },
  // Historian Challenges
  {
    personaId: 'historian',
    challengeId: 1,
    title: 'Your task is to craft a prompt for an AI to generate a detailed, first-person description of the daily life of a merchant in Ancient Rome.',
    scenario: 'For your upcoming book on the commerce of the Roman Empire, you want to write a chapter that immerses the reader in the world of a typical olive oil merchant in Rome, circa 79 AD. You need to capture the sensory details of the market, the social interactions, business dealings, and the underlying anxieties of living in a bustling, and often dangerous, ancient metropolis. Your prompt should ask for a narrative that is both historically accurate and personally engaging.',
  },
  {
    personaId: 'historian',
    challengeId: 2,
    title: 'You have found a historical letter. Your task is to craft a prompt that asks an AI to analyze the letter\'s tone, identify key themes, and explain its historical significance.',
    scenario: 'While archiving documents in a university library, you\'ve discovered a previously unknown letter from a field nurse to her family, written just after the Battle of Gettysburg during the American Civil War. The letter seems to contain unique details about medical practices and the emotional state of the soldiers. You need to quickly assess its importance for a potential academic paper. The prompt should guide the AI to perform a multi-faceted analysis of the document\'s content and context.',
  },
  {
    personaId: 'historian',
    challengeId: 3,
    title: 'Your task is to craft a prompt asking an AI to summarize the primary causes of the French Revolution for a high school history class.',
    scenario: 'You are a history teacher preparing a lesson plan. You need a concise, easy-to-understand summary of the main causes of the French Revolution. The summary should cover the key factors: social inequality (the Three Estates), economic troubles (debt and taxation), and the influence of Enlightenment ideas. Your prompt should ask the AI to create a summary in bullet points, suitable for 10th-grade students.',
  },
  {
    personaId: 'historian',
    challengeId: 4,
    title: 'Your task is to craft a prompt that generates a hypothetical conversation between two historical figures.',
    scenario: 'For a creative history blog post, you want to imagine a conversation between Leonardo da Vinci and Steve Jobs. The conversation should revolve around their shared passions for innovation, design, and the intersection of art and technology. Your prompt should ask the AI to write a short, insightful dialogue where they discuss their philosophies and react to each other\'s inventions.',
  },
  {
    personaId: 'historian',
    challengeId: 5,
    title: 'Your task is to craft a prompt to explain the historical context and significance of the Rosetta Stone.',
    scenario: 'A museum is creating a new exhibit and needs a short, engaging description for the display about the Rosetta Stone. The text needs to be accessible to the general public. Your prompt should ask the AI to explain what the Rosetta Stone is, why its discovery was so important for understanding ancient Egyptian hieroglyphs, and the story of its decipherment.',
  },
  {
    personaId: 'historian',
    challengeId: 6,
    title: 'Your task is to craft a prompt to generate a research outline for a paper on the Silk Road.',
    scenario: 'You are a university student starting a research paper on the impact of the Silk Road. You need a structured outline to guide your research and writing. Your prompt should ask the AI to create a detailed research paper outline, including an introduction with a thesis statement, main body paragraphs (e.g., Economic Impact, Cultural Exchange, Spread of Religions/Technology), and a conclusion.',
  },
  {
    personaId: 'historian',
    challengeId: 7,
    title: 'Your task is to craft a prompt to create a timeline of key events during the Space Race.',
    scenario: 'You are creating a visual aid for a presentation on the Cold War. You need a clear, chronological timeline of the most important events of the Space Race between the USA and the USSR, from the launch of Sputnik to the Apollo moon landing. Your prompt should ask the AI to generate a timeline with at least 8-10 key events, including the date and a brief description of each event\'s significance.',
  },
  {
    personaId: 'historian',
    challengeId: 8,
    title: 'Your task is to craft a prompt to compare and contrast two historical empires.',
    scenario: 'For a comparative history essay, you need to analyze the similarities and differences between the Roman Empire and the Han Dynasty in China. The analysis should cover their political structures, economic systems, technological achievements, and eventual decline. Your prompt should ask the AI to generate a structured comparison in a table format for easy reference.',
  },
  {
    personaId: 'historian',
    challengeId: 9,
    title: 'Your task is to craft a prompt to write a "Day in the Life" script for a historical documentary about a Viking shield-maiden.',
    scenario: 'You are a writer for a historical documentary series. The next episode is on Viking society. You want to create a segment that follows a shield-maiden for a day, showing her life is not just about battle but also farming, family, and social duties. Your prompt should ask the AI to write a short, voice-over script that is historically plausible and brings her world to life.',
  },
  {
    personaId: 'historian',
    challengeId: 10,
    title: 'Your task is to craft a prompt that explains a complex historical concept, like "feudalism," in simple terms.',
    scenario: 'You are tutoring a middle school student who is confused about the concept of feudalism in medieval Europe. You need a simple analogy to help them understand the relationships between lords, vassals, and serfs. Your prompt should ask the AI to explain feudalism using a simple analogy (like a modern-day franchise or a school hierarchy) and a clear, concise definition.',
  },
  {
    personaId: 'historian',
    challengeId: 11,
    title: 'Your task is to craft a prompt to generate a primary source analysis worksheet.',
    scenario: 'As a history teacher, you want your students to practice analyzing primary source documents. You have a political cartoon from the American Progressive Era depicting Teddy Roosevelt as a "trust buster." Your prompt should ask the AI to create a worksheet with a series of questions that guide students to analyze the cartoon, including questions about symbolism, context, the artist\'s perspective, and the main message.',
  },
  {
    personaId: 'historian',
    challengeId: 12,
    title: 'Your task is to craft a prompt to generate a historical "what if" scenario for a debate.',
    scenario: 'You are organizing a history club debate. You want a compelling "what if" scenario to spark discussion. The topic is: "What if the Library of Alexandria had never been destroyed?" Your prompt should ask the AI to write a short introduction to this counterfactual scenario, outlining the potential long-term consequences on science, technology, and culture, to serve as the basis for the debate.',
  },
  // HR Manager Challenges
  {
    personaId: 'hr-manager',
    challengeId: 1,
    title: 'Your task is to craft a prompt to generate a comprehensive and appealing job description for a Senior UX Designer that will attract top-tier talent in a competitive market.',
    scenario: 'Your tech company is launching a new flagship application and needs to hire an exceptional Senior UX Designer. The market is incredibly competitive. You need to write a job description that not only outlines the technical skills and responsibilities but also showcases the company\'s innovative culture and the impactful nature of the project to attract the best of the best. The prompt should specify the key elements that make a job description stand out from the crowd.',
  },
  {
    personaId: 'hr-manager',
    challengeId: 2,
    title: 'Your task is to craft a prompt for an AI to write a welcoming and informative onboarding email that clearly outlines a new remote employee\'s first-day schedule.',
    scenario: 'A new software developer is joining your remote-first company next Monday. It\'s crucial that their onboarding experience is smooth and makes them feel like part of the team from day one. You need to draft a warm, welcoming email that provides a clear schedule for their first day, including virtual meet-and-greets, system setup sessions, and an introduction to their mentor. The prompt should emphasize the desired tone and the essential information to include.',
  },
  {
    personaId: 'hr-manager',
    challengeId: 3,
    title: 'Your task is to craft a prompt to generate a set of behavioral interview questions for a "Teamwork" competency.',
    scenario: 'You are preparing to interview candidates for a Project Manager role where collaboration is critical. You need to assess their ability to work effectively in a team. Your prompt should ask the AI to generate five behavioral interview questions that probe past experiences related to teamwork, conflict resolution, and communication within a group setting.',
  },
  {
    personaId: 'hr-manager',
    challengeId: 4,
    title: 'Your task is to craft a prompt to write a sensitive and professional email declining a job applicant.',
    scenario: 'You have interviewed several strong candidates for a marketing position. You\'ve made your final choice, and now you need to inform the other qualified applicants that they were not selected. You want to be respectful and encouraging. Your prompt should ask the AI to write a polite and personalized rejection email that thanks the candidate for their time and leaves a positive impression of the company.',
  },
  {
    personaId: 'hr-manager',
    challengeId: 5,
    title: 'Your task is to craft a prompt to create an outline for a new company-wide "Work From Home" policy.',
    scenario: 'Your company is officially moving to a hybrid work model. You need to create a formal policy document that outlines the guidelines and expectations for employees. Your prompt should ask the AI to create a policy outline, including sections on eligibility, communication expectations, equipment provisioning, data security requirements, and performance management.',
  },
  {
    personaId: 'hr-manager',
    challengeId: 6,
    title: 'Your task is to craft a prompt to write a script for a manager who needs to deliver constructive feedback to an employee.',
    scenario: 'A manager needs to talk to an employee who has been consistently late for team meetings. The manager wants to address the issue constructively without demoralizing the employee. Your prompt should ask the AI to write a script for the manager using a recognized feedback model (like the Situation-Behavior-Impact model), providing talking points that are clear, specific, and focused on solutions.',
  },
  {
    personaId: 'hr-manager',
    challengeId: 7,
    title: 'Your task is to craft a prompt to brainstorm ideas for an employee wellness program.',
    scenario: 'Your company wants to improve employee well-being and reduce burnout. You have been tasked with developing a new wellness program. Your prompt should ask the AI to brainstorm a list of at least 10 diverse and inclusive wellness initiatives, covering physical health (e.g., virtual fitness classes), mental health (e.g., mindfulness app subscriptions), and financial wellness (e.g., budgeting workshops).',
  },
  {
    personaId: 'hr-manager',
    challengeId: 8,
    title: 'Your task is to craft a prompt to generate an employee satisfaction survey.',
    scenario: 'You want to gauge employee morale and identify areas for improvement within the company culture. You need to create a short, anonymous survey. Your prompt should ask the AI to generate a survey with 10 questions covering topics like work-life balance, management support, career development opportunities, and overall job satisfaction, using a mix of question types (e.g., rating scales, open-ended).',
  },
  {
    personaId: 'hr-manager',
    challengeId: 9,
    title: 'Your task is to craft a prompt to write a company-wide announcement about a new internal promotion.',
    scenario: 'A long-time employee, Jane Doe, has been promoted from Senior Analyst to Director of Data Analytics. You need to send a company-wide email to celebrate her achievement and inform the team of the transition. Your prompt should ask the AI to write a positive and professional announcement that highlights Jane\'s contributions to the company and outlines her new role and responsibilities.',
  },
  {
    personaId: 'hr-manager',
    challengeId: 10,
    title: 'Your task is to craft a prompt to create a checklist for offboarding an employee who is leaving the company.',
    scenario: 'An employee has resigned, and you need to ensure a smooth and secure offboarding process. You need a comprehensive checklist to manage all the necessary steps. Your prompt should ask the AI to create a checklist that includes tasks like knowledge transfer, retrieval of company assets (laptop, badge), deactivation of accounts, and conducting an exit interview.',
  },
  {
    personaId: 'hr-manager',
    challengeId: 11,
    title: 'Your task is to craft a prompt to write a justification for a new hire to get budget approval from finance.',
    scenario: 'The customer support team is understaffed, leading to long wait times and customer complaints. As the HR manager, you need to get approval to hire two new support specialists. You must write a formal justification for the finance department. Your prompt should ask the AI to write a persuasive memo that outlines the problem, quantifies the business impact (e.g., risk of customer churn), and shows the ROI of hiring new staff.',
  },
  {
    personaId: 'hr-manager',
    challengeId: 12,
    title: 'Your task is to craft a prompt to develop a diversity and inclusion statement for your company\'s career page.',
    scenario: 'Your company wants to attract a more diverse pool of candidates and demonstrate its commitment to an inclusive workplace. You need to write a compelling Diversity and Inclusion (D&I) statement for your public-facing career page. Your prompt should ask the AI to write a sincere and impactful D&I statement that reflects the company\'s values and commitment to creating a welcoming environment for everyone.',
  },
  // Project Manager Challenges
  {
    personaId: 'project-manager',
    challengeId: 1,
    title: 'Your task is to craft a prompt to create a detailed agenda for a project kickoff meeting that will align all stakeholders and set the project up for success.',
    scenario: 'You are leading a six-month project to develop a new mobile banking app for a major financial institution. The project involves multiple departments, including development, design, security, and marketing. You need to run a project kickoff meeting that aligns all stakeholders on the project\'s goals, scope, timeline, and communication plan to ensure a successful start. Your prompt should ask the AI to structure an agenda that is both comprehensive and time-efficient.',
  },
  {
    personaId: 'project-manager',
    challengeId: 2,
    title: 'Your task is to craft a prompt that asks an AI to identify potential risks for a critical IT project and suggest specific, actionable mitigation strategies for each risk.',
    scenario: 'You are two months into a critical project to migrate your company\'s entire e-commerce platform to a new cloud provider. The deadline is tight, and a key vendor has just informed you of potential delays in delivering essential hardware. You need to immediately identify all potential risks—technical, logistical, and financial—and develop a robust mitigation plan to present to the steering committee. The prompt should request a structured risk assessment with clear strategies.',
  },
  {
    personaId: 'project-manager',
    challengeId: 3,
    title: 'Your task is to craft a prompt to write a clear and concise project status update email for stakeholders.',
    scenario: 'It\'s the end of the sprint, and you need to send a weekly status update to all project stakeholders. The update needs to be brief but informative. Your prompt should ask the AI to write an email that summarizes what was accomplished this week, what the plan is for next week, any current blockers, and an updated project timeline status (e.g., On Track, At Risk).',
  },
  {
    personaId: 'project-manager',
    challengeId: 4,
    title: 'Your task is to craft a prompt that breaks down a large project epic into smaller user stories.',
    scenario: 'Your team is working on a new e-commerce feature with the epic "As a user, I want to be able to see personalized product recommendations." This is too big to work on. You need to break it down into smaller, manageable user stories for the development team. Your prompt should provide the epic and ask the AI to generate at least five smaller user stories in the format "As a [user type], I want [goal] so that [benefit]."',
  },
  {
    personaId: 'project-manager',
    challengeId: 5,
    title: 'Your task is to craft a prompt to create a communication plan for a new project.',
    scenario: 'You are starting a project with team members and stakeholders across different time zones. Clear communication is essential. You need to create a formal communication plan. Your prompt should ask the AI to create a plan in a table format, outlining the type of communication (e.g., status report, team meeting), the audience, the frequency, the communication channel (e.g., email, Slack, Teams), and the owner.',
  },
  {
    personaId: 'project-manager',
    challengeId: 6,
    title: 'Your task is to craft a prompt to write a project closure report.',
    scenario: 'The project to redesign the company website is now complete. You need to write a final project closure report to document the project\'s outcomes, successes, and lessons learned. Your prompt should ask the AI to generate an outline for a project closure report, including sections for project performance against goals, final budget vs. actual spend, a summary of key achievements, and a "lessons learned" section for future projects.',
  },
  {
    personaId: 'project-manager',
    challengeId: 7,
    title: 'Your task is to craft a prompt to create a RACI chart for project tasks.',
    scenario: 'For your project, there is confusion about who is responsible for what. You need to create a RACI (Responsible, Accountable, Consulted, Informed) chart to clarify roles and responsibilities. Your prompt should provide a list of key project tasks (e.g., "Design Mockups," "Develop Frontend," "User Testing") and a list of team roles (e.g., Project Manager, UX Designer, Lead Developer, QA Tester) and ask the AI to create a RACI chart in a markdown table.',
  },
  {
    personaId: 'project-manager',
    challengeId: 8,
    title: 'Your task is to craft a prompt to mediate a disagreement between two team members about a technical approach.',
    scenario: 'Your two lead developers have a strong disagreement about which database technology to use for the new project—one prefers a traditional SQL database, and the other advocates for a NoSQL solution. The debate is delaying the project. Your prompt should ask the AI to outline a structured meeting agenda and talking points for you, the Project Manager, to facilitate a constructive discussion that focuses on project requirements and technical trade-offs rather than personal preference.',
  },
  {
    personaId: 'project-manager',
    challengeId: 9,
    title: 'Your task is to craft a prompt to draft a change request document.',
    scenario: 'The client has requested a significant new feature halfway through the project. This feature was not in the original scope. You need to formally document this "scope creep" with a change request. Your prompt should ask the AI to generate a change request document template, including fields for a description of the change, the justification for it, its impact on the project timeline, budget, and resources, and a section for stakeholder approval signatures.',
  },
  {
    personaId: 'project-manager',
    challengeId: 10,
    title: 'Your task is to craft a prompt to estimate the timeline for a small project using a work breakdown structure.',
    scenario: 'You need to plan a small internal project: creating a new employee onboarding portal. You have a list of high-level tasks. Your prompt should provide these tasks (e.g., Gather requirements, Design UI/UX, Develop backend, Develop frontend, Test, Deploy) and ask the AI to create a simple work breakdown structure (WBS) with estimated durations (in days) for each task and a total estimated project timeline.',
  },
  {
    personaId: 'project-manager',
    challengeId: 11,
    title: 'Your task is to craft a prompt to write a "lessons learned" meeting agenda.',
    scenario: 'A challenging project has just concluded. You want to run a post-mortem or "lessons learned" meeting to ensure the team learns from the experience. Your prompt should ask the AI to create a meeting agenda that encourages open and honest feedback, including sections like "What went well?", "What didn\'t go so well?", and "What will we do differently next time?". The prompt should specify that the tone should be blameless and forward-looking.',
  },
  {
    personaId: 'project-manager',
    challengeId: 12,
    title: 'Your task is to craft a prompt to create a simple budget for a project.',
    scenario: 'You need to create a high-level budget for a six-month software development project. Your prompt should ask the AI to create a budget proposal in a table format, including categories like Personnel (e.g., developers, designers), Software/Tools (e.g., subscriptions), and a contingency fund (e.g., 15% of the total). The AI should use placeholder costs to structure the budget.',
  },
  // Data Analyst Challenges
  {
    personaId: 'data-analyst',
    challengeId: 1,
    title: 'You are given a raw dataset. Your task is to craft a prompt to ask an AI to analyze sales data and summarize the key trends and insights for a quarterly business review.',
    scenario: 'Your retail company just concluded its third quarter. You have been given a raw dataset containing all sales transactions from the last three years. Your CEO needs a high-level summary of performance for the latest quarter, including key trends, top-performing product categories, and any surprising anomalies compared to previous years, for an upcoming board meeting. Your prompt should ask the AI to act as a data analyst and provide a concise, executive-level summary.',
  },
  {
    personaId: 'data-analyst',
    challengeId: 2,
    title: 'Your task is to craft a prompt to ask an AI to analyze a customer dataset and propose distinct customer segments for a targeted marketing campaign.',
    scenario: 'The marketing team wants to launch a more personalized email campaign to increase customer retention. You have a large dataset containing customer demographics, purchase history, and website interaction data. Your task is to analyze this data and identify distinct customer segments with similar behaviors and preferences, so the marketing team can tailor their messaging effectively. The prompt should define the goal of the segmentation and the types of data available.',
  },
  {
    personaId: 'data-analyst',
    challengeId: 3,
    title: 'Your task is to craft a prompt to write a Python script using the pandas library to clean a messy dataset.',
    scenario: 'You have received a CSV file with customer data that has several issues: missing values in the "age" column, inconsistent capitalization in the "city" column, and the "signup_date" is a string instead of a datetime object. Your prompt should describe these issues and ask the AI to generate a Python script using pandas to handle the missing values (e.g., by filling with the mean), standardize the text, and convert the date column to the correct data type.',
  },
  {
    personaId: 'data-analyst',
    challengeId: 4,
    title: 'Your task is to craft a prompt to generate a SQL query to find user churn.',
    scenario: 'You work for a subscription-based streaming service. You have a `users` table and a `subscriptions` table with `start_date` and `end_date`. You need to calculate the monthly churn rate for the last year. Your prompt should describe the table schemas and ask the AI to write a complex SQL query that calculates the number of users who canceled their subscription each month as a percentage of the total active users for that month.',
  },
  {
    personaId: 'data-analyst',
    challengeId: 5,
    title: 'Your task is to craft a prompt to interpret the results of an A/B test.',
    scenario: 'The product team ran an A/B test on a new "checkout" button color. You have the results: Control Group (blue button) had 10,000 visitors and 1,000 conversions. Variant Group (green button) had 10,200 visitors and 1,150 conversions. Your prompt should provide this data and ask the AI to analyze the results, calculate the conversion rates for both groups, determine the percentage lift, and explain whether the result is statistically significant (you can ask it to assume a p-value for its conclusion).',
  },
  {
    personaId: 'data-analyst',
    challengeId: 6,
    title: 'Your task is to craft a prompt to generate ideas for data visualizations for a given dataset.',
    scenario: 'You are analyzing a dataset of website traffic that includes metrics like users, sessions, bounce rate, and session duration, broken down by traffic source (e.g., Organic Search, Social, Direct). You need to create a dashboard for the marketing team. Your prompt should describe the dataset and ask the AI to suggest the best type of chart (e.g., line chart, bar chart, pie chart) to visualize each key metric and explain why that chart is a good choice.',
  },
  {
    personaId: 'data-analyst',
    challengeId: 7,
    title: 'Your task is to craft a prompt to write an executive summary of your analytical findings.',
    scenario: 'After analyzing customer feedback data, you discovered that the top reason for customer churn is "poor customer service." This insight is critical for the executive team. Your prompt should ask the AI to write a one-paragraph executive summary that clearly states this main finding, supports it with a key data point (e.g., "72% of churning customers cited service issues"), and recommends a clear action (e.g., "invest in customer service training").',
  },
  {
    personaId: 'data-analyst',
    challengeId: 8,
    title: 'Your task is to craft a prompt to generate dummy data for testing a dashboard.',
    scenario: 'You have built a new sales dashboard, but you need realistic-looking data to test it before connecting it to the live database. Your prompt should ask the AI to generate a CSV-formatted sample of 20 rows of fake sales data, with columns for `OrderID`, `Product`, `Category`, `Price`, and `SaleDate`.',
  },
  {
    personaId: 'data-analyst',
    challengeId: 9,
    title: 'Your task is to craft a prompt that explains a statistical concept like "correlation vs. causation" to a non-technical audience.',
    scenario: 'You have found a strong positive correlation between ice cream sales and swimsuit sales. A marketing executive suggests running a promotion to sell more ice cream to boost swimsuit sales. You need to explain to them the concept of "correlation does not imply causation." Your prompt should ask the AI to generate a simple, clear explanation with a real-world example to illustrate the difference.',
  },
  {
    personaId: 'data-analyst',
    challengeId: 10,
    title: 'Your task is to craft a prompt to generate a request for data from another department.',
    scenario: 'To complete your analysis of the customer journey, you need access to web server logs, which are managed by the IT department. You need to write a formal request. Your prompt should ask the AI to write a clear and concise email to the IT department, specifying the exact data you need (e.g., weblogs for the last 90 days), the format you need it in (e.g., .csv), and the business reason for your request.',
  },
  {
    personaId: 'data-analyst',
    challengeId: 11,
    title: 'Your task is to craft a prompt that helps in formulating a hypothesis for data analysis.',
    scenario: 'Your company\'s user engagement on its mobile app has been dropping. You want to analyze the data to understand why, but you need to start with a clear hypothesis. Your prompt should describe the problem and ask the AI to generate three different, testable hypotheses for the drop in engagement (e.g., "Hypothesis 1: A recent app update introduced a bug that is causing crashes for a segment of users.")."',
  },
  {
    personaId: 'data-analyst',
    challengeId: 12,
    title: 'Your task is to craft a prompt to generate code for a simple predictive model.',
    scenario: 'You have a dataset of customer information, including their age, annual income, and whether they purchased a specific product. You want to build a simple logistic regression model in Python using the scikit-learn library to predict the likelihood of a new customer making a purchase. Your prompt should describe the dataset and the goal, and ask the AI to generate the Python code to train the model and make a prediction.',
  },
  // Business Analyst Challenges
  {
    personaId: 'business-analyst',
    challengeId: 1,
    title: 'Your task is to craft a prompt for an AI to analyze a described business workflow, identify inefficiencies, and suggest specific, actionable improvements.',
    scenario: 'The customer support team at a rapidly growing SaaS company is overwhelmed. The current process for handling support tickets involves manual triage via email, leading to slow response times and lost tickets. You have been asked to map out the current process and propose a new, more efficient workflow that could involve automation and a new ticketing system. Your prompt should clearly describe the existing workflow and ask for concrete suggestions for improvement.',
  },
  {
    personaId: 'business-analyst',
    challengeId: 2,
    title: 'Your task is to craft a prompt to generate a concise and persuasive summary of your analytical findings for a senior management presentation.',
    scenario: 'After a month of analysis, you have identified several major bottlenecks in your company\'s inventory management process that are costing millions each year. You are scheduled to present your findings to senior management, but you only have five minutes. You need to create a powerful, data-driven summary that clearly explains the problem and the potential ROI of your proposed solutions. The prompt should instruct the AI to create a summary that is suitable for an executive audience.',
  },
  {
    personaId: 'business-analyst',
    challengeId: 3,
    title: 'Your task is to craft a prompt to write a set of business requirements for a new software feature.',
    scenario: 'The company wants to add a "wishlist" feature to its e-commerce website. As the business analyst, you need to write the functional requirements for the development team. Your prompt should ask the AI to generate a list of business requirements in a structured format (e.g., using user stories or numbered requirements), covering what the user should be able to do (e.g., add item, remove item, view list) and any business rules (e.g., the wishlist must be saved to the user\'s account).',
  },
  {
    personaId: 'business-analyst',
    challengeId: 4,
    title: 'Your task is to craft a prompt to create a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) for a business.',
    scenario: 'A local bookstore is struggling to compete with online retailers. The owner has hired you to help them develop a new strategy. A good first step is to conduct a SWOT analysis. Your prompt should describe the business and its situation, and ask the AI to generate a SWOT analysis in a four-quadrant format, identifying the bookstore\'s internal strengths/weaknesses and external opportunities/threats.',
  },
  {
    personaId: 'business-analyst',
    challengeId: 5,
    title: 'Your task is to craft a prompt to draw a process flow diagram using text-based notation (like Mermaid syntax).',
    scenario: 'You have analyzed the company\'s expense reporting process and want to visualize it for a presentation. The process involves an employee submitting a report, a manager approving it, and then the finance department processing the payment. Your prompt should describe these steps and ask the AI to generate a simple process flowchart using Mermaid syntax that you can then render into a diagram.',
  },
  {
    personaId: 'business-analyst',
    challengeId: 6,
    title: 'Your task is to craft a prompt to conduct a competitive analysis.',
    scenario: 'Your company is planning to launch a new project management tool. You need to analyze the top three existing competitors (e.g., Asana, Trello, Jira). Your prompt should ask the AI to create a competitive analysis matrix in a markdown table, comparing the competitors across key features (e.g., pricing, key features, target audience, and unique selling proposition).',
  },
  {
    personaId: 'business-analyst',
    challengeId: 7,
    title: 'Your task is to craft a prompt to create user interview questions to gather requirements.',
    scenario: 'You are in the discovery phase for a new mobile app for booking fitness classes. You need to interview potential users to understand their needs and pain points. Your prompt should ask the AI to generate a list of 10 open-ended interview questions to ask potential users about their current habits, frustrations, and what they would want in a new app.',
  },
  {
    personaId: 'business-analyst',
    challengeId: 8,
    title: 'Your task is to craft a prompt to write a business case for a new project.',
    scenario: 'You believe the company should invest in a new internal knowledge base to improve employee training and reduce redundant questions. To get budget approval, you need to write a compelling business case. Your prompt should ask the AI to generate an outline for a business case, including sections for the Problem Statement, Proposed Solution, Benefits, Cost-Benefit Analysis, and potential Risks.',
  },
  {
    personaId: 'business-analyst',
    challengeId: 9,
    title: 'Your task is to craft a prompt to translate technical requirements into stakeholder-friendly language.',
    scenario: 'The development team has stated that a new feature requires "migrating the user authentication service to OAuth 2.0 to support third-party logins." You need to explain this to the non-technical marketing team. Your prompt should provide the technical statement and ask the AI to rephrase it in terms of business benefits, such as "allowing users to sign in with their Google or Facebook accounts, making it faster and easier to register."',
  },
  {
    personaId: 'business-analyst',
    challengeId: 10,
    title: 'Your task is to craft a prompt to create a stakeholder map for a project.',
    scenario: 'You are starting a complex project that will affect many departments. You need to identify all the key stakeholders and plan how to engage with them. Your prompt should ask the AI to create a stakeholder map, categorizing potential stakeholders (e.g., Head of Marketing, IT Security Lead, CEO) on a power/interest grid (High Power/High Interest, High Power/Low Interest, etc.) and suggest an engagement strategy for each quadrant.',
  },
  {
    personaId: 'business-analyst',
    challengeId: 11,
    title: 'Your task is to craft a prompt to write user acceptance testing (UAT) scenarios.',
    scenario: 'A new "shopping cart" feature is ready for testing. You need to write UAT scenarios for business users to test. Your prompt should ask the AI to generate at least 5 UAT test cases, each with a clear set of steps and an expected outcome. For example, "Test Case: Add an item to the cart. Steps: 1. Navigate to a product page. 2. Click \'Add to Cart\'. Expected Outcome: The cart icon updates with the number 1, and the item appears in the cart summary."',
  },
  {
    personaId: 'business-analyst',
    challengeId: 12,
    title: 'Your task is to craft a prompt to perform a gap analysis between a current process and a desired future state.',
    scenario: 'Currently, your company\'s hiring process is manual and slow (using spreadsheets and email). The desired future state is a streamlined process using an Applicant Tracking System (ATS). You need to perform a gap analysis. Your prompt should ask the AI to identify the gaps between the current and future state in terms of process, tools, and skills, and suggest actions to bridge those gaps.',
  },
  // Cybersecurity Expert Challenges
  {
    personaId: 'cybersecurity-expert',
    challengeId: 1,
    title: 'Your task is to craft a prompt to generate a clear and effective company-wide email about how to spot and report phishing attempts.',
    scenario: 'Your company\'s threat intelligence system has detected a sophisticated spear-phishing campaign targeting employees in the finance department. The emails appear to be from the CFO and ask for urgent wire transfers. You need to immediately send a company-wide alert that is clear, non-alarming, and educates employees on how to identify these malicious emails and report them safely. Your prompt should ask the AI to write an email that is easy for non-technical staff to understand.',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 2,
    title: 'Your task is to craft a prompt for an AI to outline the key, ordered steps of a formal incident response plan for a data breach.',
    scenario: 'Your company has discovered a malware infection on a critical server that hosts customer data. It\'s unclear how deep the breach is or what data has been compromised. As the lead cybersecurity expert, you must immediately initiate the incident response protocol. You need a clear, step-by-step plan that covers containment, eradication, recovery, and post-incident analysis to manage the crisis effectively. The prompt should request a formal plan structure that can be used as a template.',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 3,
    title: 'Your task is to craft a prompt to create a set of password policy best practices for employees.',
    scenario: 'You are updating your company\'s internal security policy. You need to create a simple, clear document outlining the new password policy for all employees. Your prompt should ask the AI to generate a list of best practices, including requirements for length and complexity, advice against reusing passwords, and the importance of using multi-factor authentication (MFA).',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 4,
    title: 'Your task is to craft a prompt to explain a common cyber threat, like ransomware, to a non-technical executive board.',
    scenario: 'You need to present to the board to get funding for better endpoint protection. You need to explain the business risk of a ransomware attack in terms they will understand. Your prompt should ask the AI to write a concise, jargon-free explanation of what ransomware is, how it works, and the potential financial and reputational damage it can cause to the business.',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 5,
    title: 'Your task is to craft a prompt to generate a security checklist for developers.',
    scenario: 'You want to implement a "security by design" culture. You need to create a checklist for developers to review before they deploy new code to production. Your prompt should ask the AI to generate a security checklist that includes key items from the OWASP Top 10, such as checking for SQL injection vulnerabilities, ensuring proper authentication and access control, and using secure defaults.',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 6,
    title: 'Your task is to craft a prompt to analyze a suspicious email and determine if it is a phishing attempt.',
    scenario: 'An employee has forwarded you a suspicious email. The email claims to be from your IT department, says the user\'s password has expired, and provides a link to "reset it now." The sender\'s email address looks slightly wrong, and the link seems suspicious. Your prompt should provide the text and metadata of the email and ask the AI to analyze it, identify the red flags, and confirm whether it is likely a phishing attack.',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 7,
    title: 'Your task is to craft a prompt to create a security awareness training module outline.',
    scenario: 'You are tasked with creating a new, engaging security awareness training program for all employees. You need an outline for the first module, which will cover "Social Engineering." Your prompt should ask the AI to create a training module outline, including learning objectives, key topics to cover (e.g., phishing, pretexting, baiting), and ideas for interactive activities or quizzes.',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 8,
    title: 'Your task is to craft a prompt to write a justification for purchasing a new security tool.',
    scenario: 'You want your company to invest in a new Web Application Firewall (WAF) to protect its public-facing websites. You need to convince the CFO and CTO. Your prompt should ask the AI to write a business justification that explains what a WAF is, the types of attacks it prevents (like cross-site scripting), and the potential ROI by preventing a costly data breach.',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 9,
    title: 'Your task is to craft a prompt to generate a set of recommendations for securing a home Wi-Fi network for remote employees.',
    scenario: 'With more employees working from home, you need to provide them with guidance on how to secure their home networks to protect company data. Your prompt should ask the AI to generate a list of simple, actionable steps that non-technical users can take, such as changing the default router password, enabling WPA3 encryption, creating a guest network, and keeping firmware updated.',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 10,
    title: 'Your task is to craft a prompt to role-play a threat modeling exercise for a new application feature.',
    scenario: 'Your company is adding a new feature that allows users to upload files. You need to think like an attacker to identify potential security vulnerabilities. Your prompt should describe the feature and ask the AI to act as a security researcher and identify potential threats (e.g., "What if a user uploads a file containing malware?") and suggest countermeasures for each threat.',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 11,
    title: 'Your task is to craft a prompt to draft a public data breach notification to customers.',
    scenario: 'Your company has experienced a data breach where customer names and email addresses were exposed. You must now notify your customers. The notification needs to be transparent, empathetic, and professional. It must clearly state what happened, what information was involved, what the company is doing about it, and what steps customers should take to protect themselves. Your prompt should ask the AI to draft this sensitive customer-facing communication.',
  },
  {
    personaId: 'cybersecurity-expert',
    challengeId: 12,
    title: 'Your task is to craft a prompt that classifies potential security events based on their severity.',
    scenario: 'You are monitoring a security information and event management (SIEM) system which is generating thousands of alerts. You need a way to quickly classify them. Your prompt should provide examples of three different security events (e.g., "1. A user had 5 failed login attempts." "2. Malware was detected and quarantined on a single laptop." "3. Unusual data exfiltration detected from a database server.") and ask the AI to classify each event as Low, Medium, or High severity and provide a brief justification.',
  },
];
